# Generated by Django 4.2.6 on 2023-11-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'is_correct')},
        ),
    ]
